# Generated by Django 5.1.1 on 2024-10-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafariPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('people', models.CharField(max_length=50)),
                ('overview', models.TextField()),
                ('image', models.ImageField(upload_to='safari_images/')),
                ('highlights', models.JSONField()),
                ('itinerary', models.JSONField()),
                ('map_embed_url', models.URLField()),
            ],
        ),
    ]
