# Generated by Django 5.1.1 on 2024-10-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkoutRequestID',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
