# Generated by Django 5.1.1 on 2024-11-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0009_paypalpayment_rename_payment_mpesapayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='status',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
