# Generated by Django 5.1.1 on 2024-11-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0010_mpesapayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
