# Generated by Django 5.1.1 on 2024-11-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0012_alter_mpesapayment_amount_alter_mpesapayment_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
