# Generated by Django 5.1.1 on 2024-12-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0013_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesapayment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mpesapayment',
            name='email',
        ),
    ]
