# Generated by Django 5.1.1 on 2024-12-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0015_remove_review_user_review_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
